apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: test-app
spec:
  project: default
  source:
    repoURL: https://github.com/sass1997/argocd-hooks.git
    targetRevision: HEAD
    path: kustomize-test-app/base
  destination:
    namespace: hooks
