apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-hook-beforehookcreation
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - name: test-curl
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "GET"
            - "https://google.com"
      restartPolicy: Never
  backoffLimit: 2
